name: frbcosmicevol
channels:
  - defaults
dependencies:
  - python=3.9
  - astropy=5.3.4
  - click=8.1.7
  - ipython=8.12.2
  - mpi4py=3.1.4
  - numpy=1.26.4
  - pandas=2.2.1
  - scipy=1.12.0
  - setuptools=68.2.2
  - matplotlib=2.7.2
  - conda-forge::emcee=3.1.4
  - conda-forge::dynesty=2.1.4
  - conda-forge::uncertainties=3.1.7
  - pip
  - pip:
    - corner=2.2.1
  # - h5py=3.9.0